CC = gcc
SRC = 0-isupper.c 1-isdigit.c 2-strlen.c 3-strcmp.c 5-strstr.c 0-memset.c 1-memcpy.c 2-strncpy.c 3-strspn.c 6-abs.c 0-strcat.c 1-strncat.c 3-islower.c 4-isalpha.c 9-strcpy.c 100-atoi.c 2-strchr.c 3-puts.c 4-strpbrk.c _putchar.c
OBJ = $(SRC:.c=.o)
NAME = libmy.a

all: $(OBJ)
	$(CC) $(OBJ) -o $(NAME)
